### ISSUE TITLE
AWS env. variables with credentials overwrite secrets.yml 

### ISSUE THREAD

**Issue by Constantin07** [k1LoW/awspec#169]
I ran into issue - if there are AWS access/secret keys defined as env. variables (e.g. AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY) then they overwrite the values defined in spec/secrets.yml.

It would be great to update Readme.md to note this fact.

Regards,
Constantin

**Comment by k1LoW** [comment]
Hi @Constantin07. Thank you for your comment.

awspec's key/secrets precedence is dependent on awsecrets.gem.
https://github.com/k1LoW/awsecrets#awsecrets-config-precedence

Regards.

**Comment by Constantin07** [comment]
Many thanks @k1LoW for advice.
