### ISSUE TITLE
add support for security_group tags

### ISSUE THREAD

**Issue by Constantin07** [k1LoW/awspec#175]
Hi,

It seems that security_group has no support for tags, e.g. have_tag.
Is it possible to add it ?

Regards,
Constantin

**Comment by k1LoW** [comment]
Thank you for good issue.

If you want to update have_tag, It is necessary to your pull request :)

Regards

**Comment by Constantin07** [comment]
No problem, although I'm new to Ruby :-) have more Python background. 
Just had a look at Contributing section - What's the best way to test the change locally before pushing?

**Comment by k1LoW** [comment]
Thank you @Constantin07 ⭐ 

- awspec (aws-sdk-ruby) have test and mock (stub). security_group testcase is [here](https://github.com/k1LoW/awspec/blob/master/spec/type/security_group_spec.rb). mock is [here](https://github.com/k1LoW/awspec/blob/master/lib/awspec/stub/security_group.rb)
- `have_tag` made by #119 . I think #199 is for your help.

**Comment by Constantin07** [comment]
Raised PR #177

**Comment by k1LoW** [comment]
Thank you great PR!!!
