### ISSUE TITLE
security_group_count for EC2

### ISSUE THREAD

**Issue by sveronese** [k1LoW/awspec#200]
Hello @k1LoW

do you think is possible add a security_group_count to ec2 in order to test the number of SG attached to an EC2 instance. As today I need to validate the name of security group attached and also the number, in order to not miss eventual SG manually attached to EC2.

Something like:

```
describe ec2('TEST EC2') do
   it { should exist }
   it { should be_running }
   it { should have_security_group('TEST SG') }
   its(:security_group_count) { should eq 1 }
end
```

Thank you.
Simone

**Comment by CarlInglisBJSS** [comment]
I implimented this for our route tables by having a little Ruby script that used the AWS SDK to count the subnets. Shouldn't be difficult to impliment using the SDK to count the SGs for your instance.

**Comment by sveronese** [comment]
@CarlInglisBJSS thank you for your answer. I tried to implement in awspec with something like in type/ec2.rb 

```
    def security_group_count
      resource_via_client.security_groups.reduce(0) do |sum, sg|
       sum += sg.group_id.count  
      end
    end
```

But it seems I have something like:

```
     Failure/Error: its(:security_group_count) { should eq 1 }

     NoMethodError:
       undefined method `security_group_count' for #<Aws::EC2::Instance id="i-0b48e61d85ea5ee57">
     # /Users/sveronese/.rvm/gems/ruby-2.2.4@awspec/gems/awspec-0.61.0/lib/awspec/resource_reader.rb:11:in `method_missing_via_black_list'
     # /Users/sveronese/.rvm/gems/ruby-2.2.4@awspec/gems/awspec-0.61.0/lib/awspec/resource_reader.rb:51:in `method_missing'
     # /Users/sveronese/.rvm/gems/ruby-2.2.4@awspec/gems/awspec-0.61.0/lib/awspec/resource_reader.rb:11:in `method_missing_via_black_list'
     # /Users/sveronese/.rvm/gems/ruby-2.2.4@awspec/gems/awspec-0.61.0/lib/awspec/type/base.rb:62:in `method_missing'
     # ./spec/sg_spec.rb:14:in `block (2 levels) in <top (required)>'
```

I think I didn't understand the logic of the application for the moment, still digging.

**Comment by CarlInglisBJSS** [comment]
@sveronese That's pretty much how I'd approach it. I don't know the applicaton logic that well myself, if I get time at the weekend I'll take a look - I'm now interested in knowing more. :)

**Comment by k1LoW** [comment]
Hi @sveronese 

```
its(:security_group_count) { should eq 1 }
```

LGTM!
