### ISSUE TITLE
support for ALB

### ISSUE THREAD

**Issue by kief** [k1LoW/awspec#203]
Is there a way to test ALB and related resources with awspec as it is? Or does this need to be added as a new set of types?

**Comment by k1LoW** [comment]
Hi @kief 

I think `need new set of types`

## ALB

http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html

## ELB

http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancing/Client.html
