### ISSUE TITLE
Wrong output message for have_tag

### ISSUE THREAD

**Issue by walterdolce** [k1LoW/awspec#206]
Hi,
Given the following spec:
```
describe vpc('main-vpc') do
  it { should exist }
  it { should have_tag('Environment').value('development') }
end
```
There follows the output below:
```
vpc 'main-vpc'
  should exist
  should have tag "Environment"
```

Shouldn't the message be "_should have tag *value* "development_""?

Version of `awspec` used is `0.61.1`

**Comment by k1LoW** [comment]
Hi @walterdolce 

> Shouldn't the message be "should have tag value "development""?

`have_tag` checks is not "tag value (and key)" but "tag key (and value)".

So, I think

best output is

```
should have tag "Environment" value "development"
```

better output is

```
should have tag "Environment"
```

**Comment by walterdolce** [comment]
How about:
_should have tag "Environment"_ with\ _value "development"_?

**Comment by glasswalk3r** [comment]
@k1LoW , this one is already implemented for a long time, we can close it.

**Comment by k1LoW** [comment]
@glasswalk3r Thank you!
