### ISSUE TITLE
Allow inclusion of tfvars file

### ISSUE THREAD

**Issue by minac** [k1LoW/awspec#217]
awspec is often used in conjuntion with terraform. Terraform allows us to create AWS infrastructures with code and it stores its variables in a tfvars file. It would be great if we could import that file into the *spec file and use its contents as variables from there on out.

Example of tfvars file:
```
myEc2 = "myServer"
myAmi = "ami-b9b394ca"
```

Example of what *spec file would look like:
```
require terraform.tfvars

describe ec2(myEc2) do
  it { should exist }
  it { should be_running }
  its(:image_id) { should eq myAmi }
  its(:instance_type) { should eq 't2.micro' }
end
```

I'm not a ruby dev so I'm not sure this can be done, so I leave it to your consideration. Thanks.

**Comment by k1LoW** [comment]
Hi @minac 

Terraform support JSON format var file ( https://www.terraform.io/intro/getting-started/variables.html ).

So, you use `json` like this.

```json
{
"myEc2": "myServer",
"myAmi":"ami-b9b394ca"
}
```

```ruby
require 'json'

json_file_path = '/path/to/tfvars.json'

tfvars = JSON.parse(File.read(json_file_path))

describe ec2(tfvars.myEc2) do
  it { should exist }
  it { should be_running }
  its(:image_id) { should eq tfvars.myAmi }
  its(:instance_type) { should eq 't2.micro' }
end
```

**Comment by minac** [comment]
That is great!

I tried it however and it is not working as expected.

Vars file
```
{
	"tf_env": "live"
}
```

Spec file
```
require 'spec_helper'
require 'json'

tfvars_path = File.absolute_path("terraform.json")
tfvars = JSON.parse(File.read(tfvars_path))
print tfvars.tf_env
```

Output
```
/Users/.../aws_spec.rb:6:in `<top (required)>': undefined method `tf_env' for #<Hash:0x007fac88a05f28> (NoMethodError)
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `load'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1435:in `block in load_spec_files'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `each'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/configuration.rb:1433:in `load_spec_files'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:100:in `setup'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:86:in `run'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:71:in `run'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/migueldavid/.rvm/gems/ruby-2.2.3/gems/rspec-core-3.5.4/exe/rspec:4:in `<main>'
```

I would ideally like to do the following:
```
describe autoscaling_group(tfvars.tf_env + '-asg-be-content-services') do
  it { should exist }
end

```

Help?

**Comment by k1LoW** [comment]
Sorry I fixed comment

**Comment by minac** [comment]
Perfect! Thanks!

**Comment by sandygvs** [comment]
k1LoW am trying the same for passing port info for security group but getting error as below,
=========================================
security_group 'test_sg' inbound
     Failure/Error: its(:inbound) { should be_opened (tfvars['ssh_port']).protocol('tcp').for('10.10.0.0/16') }

     NoMethodError:
       undefined method `protocol' for 22:Integer
     # ./spec/sg_pp2.rb:8:in `block (2 levels) in <top (required)>'
=========================================
My code for SG:
**require 'spec_helper'
require 'json'
tfvars_path = 'spec/tfvars.json'
tfvars = JSON.parse(File.read(tfvars_path))
describe security_group('test_sg') do
  it { should exist }
  its(:group_name) { should eq 'test_sg' }
  its(:inbound) { should be_opened (tfvars['ssh_port']).protocol('tcp').for('10.10.0.0/16') }
  it { should belong_to_vpc('test_vpc') }
end**

Any help is much appreciated...
