### ISSUE TITLE
Resources with the same name make the specs fail

### ISSUE THREAD

**Issue by walterdolce** [k1LoW/awspec#223]
Hi, when there are two AWS resources with the same name but belonging to different entities, `awspec` fails the tests.

For example, assume there are 2 VPCs with 2 Security Groups:
```
vpc-1 
vpc-2

my-security-group => vpc-1
my-security-group => vpc-2
```

The following test will fail:
```
describe security_group('my-security-group') do
  it { should exist }
end
```

I'm not sure how I would approach this.

1) Should `awspec` say something "there is a name conflict, as there are two resources with the same name"?
2) Should there be another way to target a specific resource when there is another one with the same name?

**Comment by k1LoW** [comment]
Hi @walterdolce 

> Should awspec say something "there is a name conflict, as there are two resources with the same name"?

awspec throw `Awspec::DuplicatedResourceTypeError`.

> Should there be another way to target a specific resource when there is another one with the same name?

Use security_group's id, like `sg-s123e123`.

(see https://github.com/k1LoW/awspec/issues/166#issuecomment-236548022)

**Comment by walterdolce** [comment]
> Use security_group's id, like sg-s123e123.
I don't always know the security group ids upfront. I.e. when working with Terraform, you first run terraform plan, then you run terraform apply, and then you run the specs. But you have no means of dynamically getting the security group ids.

Interestingly, having two resources with the same name does not throw the exception you mentioned above.

**Comment by k1LoW** [comment]
> and then you run the specs. But you have no means of dynamically getting the security group ids.

If you use `output`, you can get security group ids.
like this.
```
output "my_security_group_id" {
  value = "${aws_security_group.my-sg.id}"
}
```
( see https://www.terraform.io/docs/configuration/outputs.html )

> Interestingly, having two resources with the same name does not throw the exception you mentioned above.

If you ok, more information.

- awspec version
- spec
- fail message

**Comment by toddmichael** [comment]
@k1LoW I really appreciate this project as well as your new [awsrm](https://github.com/k1LoW/awsrm) project. I'm finding both extremely helpful over here! I have a follow-up question to [this response](https://github.com/k1LoW/awspec/issues/223#issuecomment-277877485) above. If I've got `outputs` defined, how can I map those outputs to variables that I can use with `awspec`? I'm interested in something similar to the [attributes feature of kitchen-terraform](http://www.rubydoc.info/gems/kitchen-terraform/Kitchen/Verifier/Terraform). This would enable me to test resources not yet supported by `awsrm`. Appreciate any advice here.

**Comment by k1LoW** [comment]
> If I've got outputs defined, how can I map those outputs to variables that I can use with awspec?

For example. 

In https://www.terraform.io/intro/getting-started/outputs.html, 

```ruby
TF_OUTPUT_IP = `terraform output ip`

describe eip(TF_OUTPUT_IP) do
  it { should exist }
end
```

**Comment by glasswalk3r** [comment]
I found myself in the same situation (having multiple EC2 instances with the same tag name/value) and that's how I fixed:

```
require 'awspec'
require 'aws-sdk-ec2'

tag_name = 'tag:Name'
tag_value = 'foobar'
resolvers = {}
ec2 = Aws::EC2::Resource.new
ec2.instances({filters: [{name: "#{tag_name}", values: ["#{tag_value}"]}]}).each do |i|
  resolvers.store(i.id, i.subnet_id)
end

if resolvers.size == 0
  raise "Could not find any EC2 instance with #{tag_name} = #{tag_value}!"
end

resolvers.each_pair do |instance_id, subnet_id|
  describe ec2(instance_id) do
    it { should exist }
    it { should be_running }
    its(:image_id) { should eq 'ami-97785bed' }
    its(:instance_type) { should eq 't2.micro' }
    it { should belong_to_subnet(subnet_id) }
  end
end
```

Not sure if it is the best way to handle that, but using Terraform `output` wouldn't help in this use case because I depend on EC2 instances created by other team. :-)

Anyway, documentation should mention this details and how to handle it... I tried to submit a PR for that, but documentation for EC2 resource seems to be generated dynamically and I'm clueless what and how to change it.

**Comment by k1LoW** [comment]
> I tried to submit a PR for that, but documentation for EC2 resource seems to be generated dynamically and I'm clueless what and how to change it.

Hi @glasswalk3r . Thank you for your help.

If you want to write advanced usage about EC2,
you can write it following `### advanced`. 
https://github.com/k1LoW/awspec/edit/master/doc/_resource_types/ec2.md

and exec [`docgen`](https://github.com/k1LoW/awspec/blob/master/doc/contributing.md) 👍

**Comment by glasswalk3r** [comment]
Created PR #402 to provide that information.

**Comment by glasswalk3r** [comment]
@k1LoW , we can close this one (hey, I fixed it! `;-)` )

**Comment by k1LoW** [comment]
👍
