### ISSUE TITLE
Cloudfront Distribution its http_version

### ISSUE THREAD

**Issue by herebebogans** [k1LoW/awspec#227]
Trying out the resources_type examples for Cloudfront Distribution

My Spec 
>   .....
>   it { should exist }
>   it { should be_deployed }
>   its(:http_version) {  should eq '2' }
>   its(:comment) { should eq "My  CF Distribution." }
>   its(:enabled) { should eq true }
>   .....

Results

>   should exist
>   should be deployed
>   http_version
>     should eq "2" (FAILED - 2)
>   comment
>     should eq "My CF Distribution."
>   enabled
>     should eq true
..
>   2) cloudfront_distribution 'XXXXXXXXXX' http_version should eq "2"
>      Failure/Error: should eq '2'
> 
>        expected: "2"
>             got: nil
> 
>        (compared using ==)

Looking through lib/awspec/type/cloudfront_distribution.rb - not sure where this mapping takes place?

**Comment by k1LoW** [comment]
http_version return String, one of "http1.1", "http2"

I don't know why got `nil`.

**Comment by herebebogans** [comment]
Hi thanks for the reply.

It's strange - if I use the aws cli for the cloudfront distribution in question it shows

> aws cloudfront get-distribution --id XXXXX | grep -C 1  HttpVersion
>             },
>             "HttpVersion": "http2",
>             "Restrictions": {

If I step into  lib/awspec/type/cloudfront_distribution.rb  with pry during the spec 

> [1] pry(#<Awspec::Type::CloudfrontDistribution>)> @resource_via_client
> => #<struct Aws::CloudFront::Types::DistributionSummary
> ....
> .....

>   #<struct Aws::CloudFront::Types::Restrictions
>    geo_restriction=#<struct Aws::CloudFront::Types::GeoRestriction restriction_type="none", quantity=0, items=[]>>,
>  web_acl_id="f3238192-2d0e-431c-bf7b-ba2645dc74c6",
> http_version=nil>

**Comment by herebebogans** [comment]
Sorry - I can see the nil is coming from the sdk Aws::CloudFront::Client.list_distributions

I'll raise a bug there.

**Comment by herebebogans** [comment]
Hi - sorry for the reopen.

I did a bit more investigation and some Cloudfront distribution properties including 

> http_version

 and 

> logging

 are only populated from Aws::CloudFront::Client.get_distribution 

> lib/awspec/helper/finder/cloudfront.rb

uses AWS::CloudFront::Client.list_distributions.

**Comment by herebebogans** [comment]
Hi - I raised this against the aws-ruby-sdk project and AWS may have a fix soonn for the list_distributions api.

(https://github.com/aws/aws-sdk-ruby/issues/1421#issuecomment-279790561)

**Comment by k1LoW** [comment]
Hi @herebebogans .  Thank you for your report!!

**Comment by herebebogans** [comment]
Hi - AWS have fixed it :P

**Comment by k1LoW** [comment]
@herebebogans Thank you for your report! 👍
