### ISSUE TITLE
Network ACL have_subnet taking too long

### ISSUE THREAD

**Issue by NBJS** [k1LoW/awspec#264]
The awspec to test whether a network acl has an associated subnet takes a very long time. We have around 50 subnets and looking at `awspec/type/network_acl.rb` and `awspec/helper/finder/subnet.rb` it seems to be looping through all the subnets each time it calls the `has_subnet?` definition, which is what is taking the time. It would be good to find a way to change this to speed it up.

All other awspec tests run much faster. We have ~950 examples which finish in around 2 minutes 40 seconds.

The NACL tests alone with 59 examples takes ~8 minutes.

```
describe network_acl(expect_nacl_id) do
  it { should exist }
  it { should belong_to_vpc(expect_vpc_name) }

  subnets.each do | expected_subnet |
    it { should have_subnet(expected_subnet) }
  end
end
```

**Comment by k1LoW** [comment]
Hi @NBJS . Thank you for your report.

If you set subnet_id (not `Name` tag) as `expected_subnet`, you can test faster.
( Because no loop )

( In order to avoid tag duplication, ) If you set `Name` tag as `expected_subnet`, awspec has to check all subnets by using `describe_subnets` 

Regards.

**Comment by NBJS** [comment]
Hi @k1LoW , thanks for your response.

I have tested with subnet_ids and although it is quicker than using the name tag, it still takes a long time. This time instead of 8 minutes it took 3 minutes.

**Comment by glasswalk3r** [comment]
Are we still looking for to improve this?

I did some bench marking using a local cache from `describe_subnets` response without filters and looks promising:

```
$ ruby test.rb 
                    user     system      total        real
find_by_sub     0.051339   0.000343   0.051682 (  2.181745)
find2_by_sub    0.061501   0.000098   0.061599 (  1.143955)
find_by_cidr    0.057556   0.000000   0.057556 (  3.300872)
find2_by_cidr   0.053146   0.003496   0.056642 (  1.287103)
find_by_tag     0.021081   0.000089   0.021170 (  1.080978)
find2_by_tag    0.026609   0.000000   0.026609 (  0.584046)
```

where `find_*` refers to the original `Finder::Subnet::find_subnet` and `find2_*` refers to the function below:

```
def find_subnet2(subnet_id)
  res = $ec2_client.describe_subnets
  by_tag_name = {}
  by_cidr = {}
  subnet_ids = []

  res.subnets.each do |sub|
    by_cidr[sub.cidr_block.to_sym] = sub.subnet_id
    next if sub.tags.empty?

    sub.tags.each do |tag|
      if tag[:key].eql?('Name')
        by_tag_name[tag[:value].to_sym] = sub.subnet_id
        break
      end
    end

    subnet_ids.append(sub.subnet_id)
  end

  by_subinet_ids = Set.new(subnet_ids)

  if subnet_id.start_with?('subnet-')
    return subnet_id if by_subinet_ids.include?(subnet_id)
  end

  id_key = subnet_id.to_sym

  if $ip_matcher.match(subnet_id)
    return by_cidr[id_key] if by_cidr.key?(id_key)
  else
    return by_tag_name[id_key]
  end
end

```
Of course, we should keep the cache for the whole testing session, but that's another thing to try to implement.

**Comment by glasswalk3r** [comment]
@NBJS , I did a PR for that, could you please give it a try?

**Comment by glasswalk3r** [comment]
@k1LoW , I'm afraid the original requestor is out of reach... could you please take a look at PR #538 ?

**Comment by glasswalk3r** [comment]
@k1LoW , since PR was accepted, I think we can close this issue.

**Comment by k1LoW** [comment]
👍
