### ISSUE TITLE
Wildcard or array matching for subnets

### ISSUE THREAD

**Issue by mbainter** [k1LoW/awspec#270]
It would be nice to be able to be more flexible in tests.  For example, I usually setup my VPCs with multiple types of subnets which have controls like whether or not they have public IP addresses, what other subnets they're allowed to talk to, etc with a subnet of each class in each VPC of a region.

So, if I have a class of subnets that has only internal IPs and I don't care which one an instance is in as long as it is in one of those, I might write a test with a list of those subnet ids like so:

```ruby
  describe ec2('i-1234567') do
    let(:valid_subnets) { ['subnet-1234567', 'subnet-4567890'] }
    context 'instance definition' do
      it { should exist }
      it { should belong_to_vpc("MYVPC") }
      it { should belong_to_subnet(valid_subnets) }
    end
  end
```

Or, I might just name them all similarly, like "MYVPC Private Subnet in AZ A", such that I could then try to match based on tag:Name like so:

```ruby
  describe ec2('i-1234567') do
    let(:vpc_name) { 'MYVPC' }
    let(:valid_subnets) { vpc_name + ' Private*' }
    context 'instance definition' do
      it { should exist }
      it { should belong_to_vpc(vpc_name) }
      it { should belong_to_subnet(valid_subnets) }
    end
  end
```

**Comment by k1LoW** [comment]
Hi @mbainter .

awspec is testing framework (on Rspec ). So, I think that we should make strict comparisons.

If you want to solve it now, I write spec like 

```ruby
describe ec2('i-1234567') do
  its('subnet_id') { should eq('subnet-1234567').or eq('subnet-4567890')  }
end
```

Regards
