### ISSUE TITLE
iam_group will not find group when testing have_iam_user

### ISSUE THREAD

**Issue by dmraff** [k1LoW/awspec#276]
I am testing the users and the count of users in a group. I am able to test that a certain policy is applied to a group. In further testing I am finding have_iam_user is returning the following:

The group with name "GROUPNAME" cannot be found

Also users.count is unable to find the group

**Comment by k1LoW** [comment]
Hi @dmraff . Thank you for report!

Could you show me spec sample?

**Comment by dmraff** [comment]
It finds the that the policy is attached, but will not pass the tests on the number of members in the group or that the user is in the group

describe iam_group('groupnamehere') do
  it { should have_iam_policy('Someaccess') }
  its('users.count') { should eq 6 }
  it { should have_iam_user('username') }
end
