### ISSUE TITLE
ecs_cluster's have_container_instance fails when using "should" syntax

### ISSUE THREAD

**Issue by adamscharf** [k1LoW/awspec#277]
`ecs_cluster`'s `have_container_instance()` behavior is unlike most of the other matchers like it.

For example:

```ruby
describe launch_configuration("foo") do
    it { should have_security_group('sg-123') } # passes with message: should have security group "sg-123"
```
Is not like:
```ruby
  describe ecs_cluster("bar") do
    it { should have_container_instance('foobar') } # fails
    it { have_container_instance('foobar') } # passes with unhelpful message: example at ./test/ecs_cluster_spec.rb:9
```
The same pattern that `launch_configuration` uses is repeated in multiple locations and seems like `have_container_instance` matcher should behave the same way. Instead, however, if you use the `should` syntax, your test fails with the following error:

```shell
undefined local variable or method `arn_or_uuid' for ecs_cluster 'foobar':Awspec::Type::EcsCluster
```

**Comment by k1LoW** [comment]
Hi @adamscharf , Thank you for your report!

I'll check it
