### ISSUE TITLE
vpc_connection resource does not work when supplying name

### ISSUE THREAD

**Issue by Evesy** [k1LoW/awspec#291]
Hi,

When checking the existence of a VPN connection using the `vpn_connection` resource, it fails to return/find anything if the name is specified rather than the ID.

```
  describe vpn_connection("sandbox-vpn-dc2") do
    it { should exist }
  end
```

```
begin exception VPN vpn_connection 'sandbox-vpn-dc2' should exist expected vpn_connection 'sandbox-atcloud-dc2' to exist end exception
    should exist (FAILED - 2)
```

If I do the same however using the VPN ID, it successfully finds the existence of the VPN:
```
  describe vpn_connection("vpn-abc123") do
    it { should exist }
  end
```

```
 vpn_connection 'vpn-abc123'
    should exist
```

If there's any useful debug information I can provide please let me know, I'm not all too familiar with this!

### Environment
aws-sdk (2.9.44)
awspec (0.81.1)
rspec (3.6.0)

**Comment by k1LoW** [comment]
@Evesy Thank you for your report!!

`vpn_connection` resource type is not support `tag:Name` now.
https://github.com/k1LoW/awspec/blob/48b2b69668161c2b7340fd7e050633f4653fdf4b/lib/awspec/helper/finder/ec2.rb#L56

I'll fix it.
