### ISSUE TITLE
s3 bucket versioning returns incorrect result

### ISSUE THREAD

**Issue by damacus** [k1LoW/awspec#298]
Hi, 

I have the resource below declared. It incorrectly returns an error on versioning.

```ruby
describe s3_bucket('X') do
  it { should exist }
  it { should have_versioning_enabled }
end
```

Error: `expected #has_versioning_enabled? to return true, got false`

When I query via the command line: 
```bash
aws s3api get-bucket-versioning --bucket X
{
    "Status": "Enabled",
    "MFADelete": "Disabled"
}
```

If I query via the Ruby SDKv2
```ruby
require 'aws-sdk'
bucket_name = 'X'
s3 = Aws::S3::Resource.new(region: 'us-west-1')
bucket.versioning.status
=> "Enabled"
```

**Comment by damacus** [comment]
Bit more digging, but this method *looks* correct: 
https://github.com/k1LoW/awspec/blob/master/lib/awspec/type/s3_bucket.rb#L80

**Comment by k1LoW** [comment]
Hi @damacus Thank you for your report!

**Comment by damacus** [comment]
Happy to submit a patch if I can be pointed in the right direction! :)

**Comment by damacus** [comment]
Looks like somewhere in the config it isn't/wasn't reading the correct region(!) 

Thanks!
