### ISSUE TITLE
route53_hosted_zone's have_record_set spec does not work only `have_record_set`

### ISSUE THREAD

**Issue by walterdolce** [k1LoW/awspec#318]
Hi,

Provided I have a hosted zone `foo`, with a record `bar`, the following spec will return an error, contradicting what the doc says:
```
describe route53_hosted_zone('foo.') do
  it { should have_record_set('bar.foo.') }
end

============

route53_hosted_zone 'foo.'
  should have record set "bar.foo." (FAILED - 1)

Failures:

  1) route53_hosted_zone 'foo.' should have record set "bar.foo."
     Failure/Error: it { should have_record_set('bar.foo.') }

     TypeError:
       no implicit conversion of nil into String
     # ./spec/route53_spec.rb:2:in `block (2 levels) in <top (required)>'
```

**Comment by k1LoW** [comment]
Hi @walterdolce 
Could you show your hosted_zone settings on AMC ?

**Comment by walterdolce** [comment]
Hi @k1LoW, the hosted zone is a normal public hosted zone. Has no tags assigned to it. It has a comment and a bunch of name servers. Does that help?

**Comment by k1LoW** [comment]
`have_record_set` need chained method ( like `.a()` `.mx()` )

Could you execute `awspec generate route53_hosted_zone foo.` ?

**Comment by walterdolce** [comment]
Using `.a()`, etc requires me to know the value of it. What if that value comes and go? What if I don't want to know the value of `A` or `TXT` ?

What I'm saying is, can `awspec` answers assertions like:
- Make sure record `bar` exist(s) within the hosted zone `foo`
- Make sure redord `bar` of type `A` exists within the hosted zone `foo`, _but I don't care about the value of `A`

Hope that makes sense.

**Comment by k1LoW** [comment]
@walterdolce Thank you for your request.

> Using .a(), etc requires me to know the value of it. What if that value comes and go? What if I don't want to know the value of A or TXT ?

There is no way to solve it now. and I will not fix it now. 

It is necessary to your pull request :)

Regards.

**Comment by NBJS** [comment]
@walterdolce you could use the AWS SDK to get the record set value and supply it as a variable to .a() 

` it { should have_record_set(expected_record_set_name).a(live_value).ttl(aname_expected_ttl) }`

I am using this method.

**Comment by walterdolce** [comment]
@NBJS that's what I want to avoid. To use more to accommodate the tool.

We should be able to do something like:
```
should have_record_set_a(expected_record_set_name)
```
This is to simply answer the question: do I have `expected_record_set_name` as a `A` record in the hosted zone `foo`?

The question does not care about the TTL or anything else. I hope this makes sense!

I'll be happy to send the PR as soon as I get some free development time :-)

**Comment by NBJS** [comment]
Yeah, I understood what you wanted to do, I was just offering a work around. In our case we do care about the other values.
