### ISSUE TITLE
Separate alb resource type into alb and nlb

### ISSUE THREAD

**Issue by k1LoW** [k1LoW/awspec#319]
https://aws.amazon.com/jp/blogs/aws/new-network-load-balancer-effortless-scaling-to-millions-of-requests-per-second/

http://docs.aws.amazon.com/sdkforruby/api/Aws/ElasticLoadBalancingV2/Client.html#describe_load_balancers-instance_method

**Comment by gmccue** [comment]
@k1LoW it looks like #320 simply filters out `nlb`, is that right? I wouldn't mind adding an `nlb` Finder in a PR.

**Comment by k1LoW** [comment]
Hi @gmccue . Thank you for a wonderful suggestion.

> it looks like #320 simply filters out nlb, is that right?

YES

> I wouldn't mind adding an nlb Finder in a PR.

Thank you!!! 👍 👍 👍 . I have never used nlb so I do not know if the nlb matcher is the same as alb matcher.

I'm really happy if you help me.

**Comment by FlanBr-yopG** [comment]
@gmccue , @k1LoW , does this provide the NLB resource you desired? https://github.com/k1LoW/awspec/pull/346

**Comment by k1LoW** [comment]
@FlanBr-yopG Thank you !!! Fixed by #346
