### ISSUE TITLE
Support AWS SDK 3.x

### ISSUE THREAD

**Issue by darrenhaken** [k1LoW/awspec#322]
Would you upgrade to AWS SDK 3 as that has now been released?

Happy to update the Gemspec and give a PR if you want but with it being a one-line code change I wasn't sure if it was worth it 😄

**Comment by k1LoW** [comment]
> Would you upgrade to AWS SDK 3 as that has now been released?

Yes!

> Happy to update the Gemspec and give a PR if you want but with it being a one-line code change I wasn't sure if it was worth it

No. need some changes.

I making PR (link https://github.com/k1LoW/awspec/pull/316) now. please wait to merge 👍

**Comment by darrenhaken** [comment]
When will this be merged?

**Comment by k1LoW** [comment]
@darrenhaken 

I'm thinking to release v 1.0.0 at the end of this month. At that time I will update aws-sdk to v3.x.

**Comment by k1LoW** [comment]
v1.0.0 released.
