### ISSUE TITLE
external_id is not used when assuming a role.

### ISSUE THREAD

**Issue by craigmonson** [k1LoW/awspec#327]
This is specifically a problem with the https://github.com/k1LoW/awsecrets gem.  There is an outstanding PR (https://github.com/k1LoW/awsecrets/pull/17) for a fix, so once that's merged, versioned and pushed to rubygems, we need to bump the version in the gemfile in this project to pick up the changes.  I do not think there are any modifications beyond that to be made.

**Comment by k1LoW** [comment]
!!! @craigmonson !!! I just released awsecrets v1.14.0 !!!

**Comment by k1LoW** [comment]
Fixed in #329
