### ISSUE TITLE
pending count not working for ecs_service

### ISSUE THREAD

**Issue by rgokhale** [k1LoW/awspec#340]
I am running awspec inside kitchen-terraform, when I try to use the pending count method for ecs_service, its errors out as follows
```
 undefined method `pending_count' for ecs_service 'xyz':Awspec::Type::EcsService
```

Its also fails the service exists test witht he following error
```
expected ecs_service 'xyz' to exist
```

I am very sure the service exists in the cluster.

Any help will be appreciated.

Thanks,
Rishi

**Comment by k1LoW** [comment]
Hi @rgokhale ! Thank you for your report !!

You'll need to provide a little more information than that.

- awspec version ( `awspec -v` )
- Ruby version ( `ruby -v` )
- awspec code

Regards. ⭐️

**Comment by rgokhale** [comment]
Here are some more details

awspec version = 1.0.0
ruby version = 2.3.1

As I mentioned earlier I am running this inside kitchen-terraform, here is my code

```
require "awspec"

cluster_name =  attribute "cluster_name", {}
service_name =  attribute "service_name", {}


control 'ecs_service' do
  describe 'ecs_service' do
    let :example_ecs_service do
      ecs_service(
        service_name,
         cluster: cluster_name
     )
    end

    describe "service_exists" do
      subject do example_ecs_service end
      it "exists" do is_expected.to exist end
    end

    describe "service_active" do
      subject do example_ecs_service end
      it "is active" do is_expected.to be_active end
    end

    describe "desired_count" do
      subject do example_ecs_service.desired_count end
      it "1" do is_expected.to eq 1 end
    end

    describe "running_count" do
      subject do example_ecs_service.running_count end
      it "1" do is_expected.to eq 1 end
    end

    describe "pending_count" do
      subject do example_ecs_service.pending_count end
      it "0" do is_expected.to eq 0 end
    end
  end
end

```

Note that desired_count and running_count also give the same error. FWIW it seems that the cluster isn't being set properly, its is still default.

I also tried hardcoding the service and cluster values to rule out any issues with my code that sets cluster_name and service_name.

I am also seeing the same issues with ecs_container_instance, where it cant find some of the methods like agent_connected.

Any help is appreciated.

Thanks very much.

Rishi

**Comment by k1LoW** [comment]
Could you check following spec? ( awspec recommended )

```ruby
require 'awspec'

describe ecs_service(service_name), cluster: cluster_name  do
   it { should exist }
   its(:cluster) { should eq cluster_name }
   its(:desired_count) { should eq 1 }
   its(:pending_count) { should eq 0 }
end
```

**Comment by sandygvs** [comment]
Hi @k1LoW 

Am running awspec for ecs service by referring https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#ecs_service where am facing below error,

**ecs_service 'dev-1-organization' network_configuration should eq ["subnets=[\"subnet-xxxx, subnet-xxx\"]", "security_groups=[\"sg-xxx\"]", "assign_public_ip=\"DISABLED\""]
    Failure/Error: its(:network_configuration) { should eq ['subnets=["subnet-xxx, subnet-xxx"]', 'security_groups=["sg-xxx"]', 'assign_public_ip="DISABLED"'] }

      expected: ["subnets=[\"subnet-xxx, subnet-xxx\"]", "security_groups=[\"sg-xxx\"]", "assign_public_ip=\"DISABLED\""]
           got: #<struct Aws::ECS::Types::NetworkConfiguration awsvpc_configuration=#<struct Aws::ECS::Types::AwsVpcC..."subnet-xxx"], security_groups=["sg-xxx"], assign_public_ip="DISABLED">>

      (compared using ==)

      Diff:
      @@ -1,4 +1,2 @@
      -["subnets=[\"subnet-xxx, subnet-xxx\"]",
      - "security_groups=[\"sg-xxx\"]",
      - "assign_public_ip=\"DISABLED\""]
      +"#<struct Aws::ECS::Types::NetworkConfiguration awsvpc_configuration=#<struct Aws::ECS::Types::AwsVpcC...\"subnet-xxx\"], security_groups=[\"sg-xxx\"], assign_public_ip=\"DISABLED\">>"

    # C:/Users/abcd/Terraform + InSpec/SAM/awspec/spec/ecs.rb:xx:in `block (2 levels) in <top (required)>'**

Below is the ecs.rb file,
**describe ecs_service('dev-1-organization'), cluster: 'dev-1-microservice' do
its(:network_configuration) { should eq ('subnets=["subnet-xxx, subnet-xxx"]', 'security_groups=["sg-xxx"]', 'assign_public_ip="DISABLED"') }
end**

Much appreciate your help on this...

Thanks & Regards,
Santhosh

**Comment by glasswalk3r** [comment]
@k1LoW , I guess this one can be close since there is a long time waiting for requester feedback.
