### ISSUE TITLE
Error executing "awspec init"

### ISSUE THREAD

**Issue by ReenaAcharya** [k1LoW/awspec#354]
Hi,

I am trying to install awspec. I have been able to install awspec.
But when I executed "awspec init" it gave me following error:-

awspec init
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require': /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/type/elb.rb:52: syntax error, unexpected ',' (SyntaxError)
...   def has_listener?(protocol:, port:, instance_protocol:, i...
...                               ^
/usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/type/elb.rb:60: syntax error, unexpected keyword_end, expecting end-of-input
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:12:in `block in <module:Type>'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:11:in `each'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:11:in `<module:Type>'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:3:in `<module:Helper>'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:2:in `<module:Awspec>'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper/type.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec/helper.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/lib/awspec.rb:10:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/local/share/ruby/gems/2.0/gems/awspec-0.14.0/bin/awspec:3:in `<top (required)>'
        from /usr/local/bin/awspec:23:in `load'
        from /usr/local/bin/awspec:23:in `<main>'
"

**Comment by inokappa** [comment]
Hi, @ReenaAcharya 

* You seem to need to use awspec with Ruby 2.1 or higher, what is the Ruby version you are using?
    * https://rubygems.org/gems/awspec/ 
* The version of awspec you are using is very old, so we recommend using the latest version
    * your version: 0.14.0 / latest version: 1.40.1

Regards.

Yohei

**Comment by ReenaAcharya** [comment]
Hi @inokappa,

Thank you for the reply.
I just checked my ruby version which is "ruby 2.0.0p648 (2015-12-16) [x86_64-linux]"
I also exported ruby path to $PATH.
but again when I did "awspec init". I got following error:-
/usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/jmespath-1.3.1/lib/jmespath.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/aws-sdk-core-2.1.36/lib/aws-sdk-core.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/aws-sdk-resources-2.1.36/lib/aws-sdk-resources.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/aws-sdk-2.1.36/lib/aws-sdk.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/type/base.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:12:in `block in <module:Type>'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:11:in `each'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:11:in `<module:Type>'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:3:in `<module:Helper>'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:2:in `<module:Awspec>'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper/type.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec/helper.rb:1:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/awspec-0.14.0/lib/awspec.rb:10:in `<top (required)>'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /usr/share/ruby/vendor_ruby/2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /root/.gem/gems/awspec-0.14.0/bin/awspec:3:in `<top (required)>'
        from /usr/local/bin/awspec:23:in `load'
        from /usr/local/bin/awspec:23:in `<main>'

**Comment by ReenaAcharya** [comment]
Hi @inokappa ,
I am able to do "awspec init"

Thanks.
