### ISSUE TITLE
Error when executing "bundle exec rake spec"

### ISSUE THREAD

**Issue by ReenaAcharya** [k1LoW/awspec#355]
Hi,

When executing "bundle exec rake spec", I got following error:-

/usr/local/rvm/rubies/ruby-2.2.4/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.4/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.2.4/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.2.4/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading ./spec/name_spec.rb.
Failure/Error: Awsecrets.load(secrets_path: File.expand_path('./secrets.yml', File.dirname(__FILE__)))

NameError:
  uninitialized constant Awsecrets
# ./spec/spec_helper.rb:2:in `<top (required)>'
# ./spec/name_spec.rb:1:in `require'
# ./spec/name_spec.rb:1:in `<top (required)>'
No examples found.

Finished in 0.00035 seconds (files took 0.17965 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

/usr/local/rvm/rubies/ruby-2.2.4/bin/ruby -I/usr/local/rvm/gems/ruby-2.2.4/gems/rspec-core-3.7.1/lib:/usr/local/rvm/gems/ruby-2.2.4/gems/rspec-support-3.7.1/lib /usr/local/rvm/gems/ruby-2.2.4/gems/rspec-core-3.7.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed

Thanks.

**Comment by k1LoW** [comment]
Hi @ReenaAcharya .

> NameError:
> uninitialized constant Awsecrets

It seems that `awsecrets` not installed.

Could you show me your environment

- Gemfile
- `bundle exec gem list | grep awsecrets` results
- `bundle exec gem list | grep awspec` results

**Comment by glasswalk3r** [comment]
@k1LoW , I would close this one since there is a long time waiting for a feedback.

**Comment by k1LoW** [comment]
👍
