### ISSUE TITLE
s3_bucket have_lifecycle_rule always returns true

### ISSUE THREAD

**Issue by jcejohnson** [k1LoW/awspec#357]
I pasted the example as-is into my test case and it fails to fail.

From my test:

>   it {should have_lifecycle_rule(  id: 'MyRuleName')}
> 
>   it do
>     should have_lifecycle_rule(
>       id: 'MyRuleName',
>       noncurrent_version_expiration: { noncurrent_days: 1 },
>       expiration: { days: 2 },
>       transitions: { days: 3, storage_class: 'GLACIER' },
>       status: 'Enabled'
>     )
>   end

From my tfstate file:

> "lifecycle_rule.#": "1",
> "lifecycle_rule.0.abort_incomplete_multipart_upload_days": "0",
> "lifecycle_rule.0.enabled": "false",
> "lifecycle_rule.0.expiration.#": "0",
> "lifecycle_rule.0.id": "tf-s3-lifecycle-20180315164522445900000002",
> "lifecycle_rule.0.noncurrent_version_expiration.#": "0",
> "lifecycle_rule.0.noncurrent_version_transition.#": "0",
> "lifecycle_rule.0.prefix": "",
> "lifecycle_rule.0.tags.%": "0",
> "lifecycle_rule.0.transition.#": "1",
> "lifecycle_rule.0.transition.2476382906.date": "",
> "lifecycle_rule.0.transition.2476382906.days": "90",
> "lifecycle_rule.0.transition.2476382906.storage_class": 
>

**Comment by inokappa** [comment]
Hi @jcejohnson 

Thank you for your report.

This issue was resolved by v1.4.3.
Please use v1.4.3.

Regards.

Yohei
