### ISSUE TITLE
Duplicate errors

### ISSUE THREAD

**Issue by jbruett** [k1LoW/awspec#368]
Just getting start using this.  Wrote a spec file, imported a bunch of ALBs and hand wrote a single EC2 instance block, everything seems to be working, except that it looks like its pulling in the file twice.  I have scrubbed some data out of the errors, anything <like this> has normal acceptable text in reality.  I used `awspec init` to build out the awspec part of the project.  My local workstation is a windows system and i'm executing from Chef DK since it has all the ruby based stuff I need to make this work (for the most part)

```
Failed examples:

rspec ./spec/dev_spec.rb:187 # ec2 '<servername>' should be disabled api termination
rspec C:/Users/jbruett/Documents/repos/<project>/terraform/dev/spec/dev_spec.rb:187 # ec2 '<servername>' should be disabled api termination
```

**Comment by k1LoW** [comment]
Hi @jbruett .

Could you show followings ?

- AWS resources you use
- awspec version ( and Ruby version )
- spec code you wrote
- all error code

**Comment by jbruett** [comment]
**awspec --version**
```terraform\dev [master ≡ +5 ~0 -0 !]> awspec --version
1.5.2
```
**ruby --version**
```
terraform\dev [master ≡ +5 ~0 -0 !]> ruby --version
ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
```
**AWS Resources** in the test file include 16 ALBs (code generated with awspec) and 1 EC2 instance, handwritten based on the example in the awspec docs and updated with accurate information for my infrastructure.

Here's an example of the code (this is for a client so I have stripped out a bunch of the values, but the structure is exactly the same.
```
describe alb('loadbalancername'), region: 'us-east-1' do
  it { should exist }
  its(:load_balancer_arn) { should eq 'loadbalancerarn' }
  its(:dns_name) { should eq 'loadbalancerdns' }
  its(:load_balancer_name) { should eq 'loadbalancername' }
  its(:scheme) { should eq 'internal' }
  its(:vpc_id) { should eq 'vpcid' }
  its(:type) { should eq 'application' }
  its(:ip_address_type) { should eq 'ipv4' }
end

describe ec2('servername'), region: 'us-east-1' do
  it { should be_running }
  its(:instance_id) { should eq 'instanceid' }
  its(:image_id) { should eq 'amiid' }
  its(:private_ip_address) { should eq 'ipaddress' }
  it { should have_security_groups(['list', 'of', 'securitygroups']) }
  it { should belong_to_vpc('vpcid') }
  it { should belong_to_subnet('subnetid') }
  it { should be_disabled_api_termination }
end
```
There is no real error code, but as you can see in the output in the first post it's calling the same file twice, and the full output indicates the same.  The first path is relative and the second is the absolute path to the same file.  I can't imagine that's expected.  One part of my output that I think indicates the issue is below, I think that the `--pattern 'spec/**{,/*/**}/*_spec.rb'` is somehow matching both paths
```
terraform\dev [master ≡ +5 ~0 -0 !]> bundle exec rake spec
C:/opscode/chefdk/embedded/bin/ruby.exe -I'C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/lib';'C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rspec-support-3.7.1/lib' 'C:/opscode/chefdk/embedded/lib/ruby/gems/2.4.0/gems/rspec-core-3.7.1/exe/rspec' --pattern 'spec/**{,/*/**}/*_spec.rb'
```

**Comment by k1LoW** [comment]
@jbruett 

I think this is not awspec error. 
Maybe RSpec or Rake execution problem.

Because,
- awspec is executed on RSpec ecosystem. 
- Your command use `rake` .

**Comment by jbruett** [comment]
So i don't disagree, after you last response I double backed and just ran`rspec .\spec\dev_spec.rb` and the issue went away and i only get a single run.  so it's definitely something with the rake task (i get the duplication regardless of running it with/without `bundle exec`).  I'm guessing its something to do with the fact that i'm using the chefdk implementation of ruby and all the things i need to make this work instead of a standalone copy of ruby and friends.  oh well, i'll just use `rspec` command to run the tests.

**Comment by jbruett** [comment]
totally something with chefdk version of the toolchain, just quickly installed ruby and the prereqs and the issue does not reappear.
