### ISSUE TITLE
Add SNS resource type

### ISSUE THREAD

**Issue by imraazrally** [k1LoW/awspec#369]
I do not see an SNS resource. Are there any plans to add this resource_type ? Thanks!

**Comment by k1LoW** [comment]
Hi @imraazrally ! Thank you for your request !
It is necessary to your pull request :)

**Comment by eamonnfaherty** [comment]
+1

**Comment by glasswalk3r** [comment]
SNS support was added and released with awspec version 1.12.1.

**Comment by k1LoW** [comment]
Thank you @glasswalk3r !!! 👍 👍 👍 👍 

I close thie issue.
