### ISSUE TITLE
Undefined method `target_key_id' for nil:NilClass

### ISSUE THREAD

**Issue by imraazrally** [k1LoW/awspec#370]
I'm receiving the following error when trying to test kms('my-kms-key-id') or kms('my-kms-key-arn') ...

```     undefined method `target_key_id' for nil:NilClass```

Any thoughts ?

**Comment by k1LoW** [comment]
Hi @imraazrally 

Could you show followings ?

- AWS resources you use
- awspec version ( and Ruby version )
- spec code you wrote
- all error code ( and command )

**Comment by joekhoobyar** [comment]
The `kms_client.list_aliases` method only lists the first page of aliases.  This is a problem we are experiencing too.

**Comment by joekhoobyar** [comment]
https://docs.aws.amazon.com/sdkforruby/api/Aws/KMS/Client.html#list_aliases-instance_method
