### ISSUE TITLE
NoMethodError: undefined method `state' for nil:NilClass ec2.rb:30:in 

### ISSUE THREAD

**Issue by IvoHelecloud** [k1LoW/awspec#383]
Hello,

I received following error when I execute "bundle exec rake spec" 

     Failure/Error: resource_via_client.state.name == state
     
     NoMethodError:
       undefined method `state' for nil:NilClass
     # ./lib/awspec/type/ec2.rb:30:in `block (2 levels) in <class:Ec2>'
     # ./spec/ec2_spec.rb:4:in `block (2 levels) in <top (required)>'

ec2_spec.rb

require 'spec_helper'

describe ec2('CloudSploit'), region: 'eu-west-1' do
  it { should be_running }
end

bundle exec gem list | grep awspec 
awspec (1.9.0)

Do you have any idea how I can fix it?

Thanks,
Ivo

**Comment by inokappa** [comment]
Hi, @IvoHelecloud.

I got the same error as you if the instance under test does not exist.

You need to verify that the EC2 instance ('CloudSploit') exists, and if you want to test the state of the EC2 instance pending or running or shutting down or terminated or stopped or stopped status It must be held. (https://github.com/k1LoW/awspec/blob/master/lib/awspec/type/ec2.rb#L23-L26)

Please confirm. ;-)
Regards.

Yohei

**Comment by glasswalk3r** [comment]
I implemented a fix in PR #439

**Comment by glasswalk3r** [comment]
@IvoHelecloud and @inokappa , could you please confirm if that fixes the issue?

**Comment by glasswalk3r** [comment]
@k1LoW, the PR #534 is already merged, so this issue can be closed by now.

**Comment by k1LoW** [comment]
👍
