### ISSUE TITLE
is it possible to replace *should* with *expect* for DynamoDB resource?

### ISSUE THREAD

**Issue by glasswalk3r** [k1LoW/awspec#385]
From the project documentation: https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#dynamodb_table, `should` is used to evaluation.
On the other hand, usage of `should` is not encouraged: https://github.com/rspec/rspec-expectations/blob/master/Should.md.
Is there any way to do this replacement? I'm bit lost because attempts like:
```
describe "Testing #{my_table}" do
    subject { dynamodb_table(my_table) }
    it 'exists in the AZ' do |example|
        expect(example).to exist
    end
    it "has the expected key schema #{my_table}-id" do
        expect(have_key_schema("#{my_table}-id").key_type('HASH')).to be_truthy
    end

end
```

Fails or produce wrong results (the table really doesn't exist, but the test passes). In this example I got this error:
```
Testing foobar
  exists in the AZ (FAILED - 1)
  has the expected key schema foobar-id

Failures:

  1) Testing foobar exists in the AZ
     Failure/Error: expect(example).to exist
       expected #<RSpec::Core::Example "exists in the AZ"> to exist but it does not respond to either `exist?` or `exists?`
     # ./spec/feedback_spec.rb:10:in `block (2 levels) in <top (required)>'

Finished in 0.03534 seconds (files took 1.8 seconds to load)
2 examples, 1 failure

Failed examples:

rspec ./spec/feedback_spec.rb:9 # Testing foobar exists in the AZ
```

**Comment by glasswalk3r** [comment]
Yes, it is. The `subject` is implicit and can be named:

```
describe dynamodb_table(my_table) do
    it do
        expect(subject).to exist
    end

    it do
        expect(subject).to have_key_schema('id').key_type('HASH')
    end
end
```

I suggest to update the documentation examples to use `expect`, as recommended by the RSpec project. If desirable, I can provide a pull request for that.

**Comment by k1LoW** [comment]
Hi @glasswalk3r !!

Thank you for your comment ( and 📬 ) !!!

awspec uses `should`, and `expect` is not particularly supported.

Because I think that `should` is easier to understand.
I do not want to follow RSpec's latest notation.

Best regards
