### ISSUE TITLE
[Feature] eks support 

### ISSUE THREAD

**Issue by amukiza** [k1LoW/awspec#389]
## [Feature] Support for EKS Cluster resource
* Thinking one would want to check that their eks cluster:-
  * is in the expected state: either of `%w("CREATING", "ACTIVE")`
  * has `resourcesVpcConfig.subnetIds = [x, y, z]`
  * has `resourcesVpcConfig.securityGroupIds = [x]` vpcId
  * has `resourcesVpcConfig.vpcId = x`
  * has `n` nodes 
  * all nodes are in `x` state 
  * any node is in `x` state 
  * e.t.c

**I am happy to pick this up** and I have started exploring the codebase. I am creating this issue to avoid duplicating efforts incase someone is already working on it.

**Comment by amukiza** [comment]
Support for EKS cluster added in [#391](https://github.com/k1LoW/awspec/pull/391). 
**WIP** Adding matchers for eks cluster nodes!

**Comment by amukiza** [comment]
@k1LoW How do you feel about splitting "adding support for eks node matchers" as a separate issue and closing this one.  It seems like a nice to have since we can use the `ec2` matchers for the nodes.

**Comment by k1LoW** [comment]
@amukiza 
> How do you feel about splitting "adding support for eks node matchers" as a separate issue and closing this one. 

I think 

- If you want to separate issue, I welcome it.
- Small Issue and Pull Request are welcome.

> I would like to prioritize adding emr support and coming back to eks-nodes later.

Thank you !! so much !!!!

**Comment by amukiza** [comment]
@k1LoW I will create a small issue for eks-nodes. It will re-use a lot of `ec2` implementation so hopefully it should straight forward.
