### ISSUE TITLE
ACM's domain_name is not unique

### ISSUE THREAD

**Issue by htnosm** [k1LoW/awspec#414]
Returns incorrect value when same domain name exists in ACM test.
I think it would be better to support testing with arn like lambda resource type.

Does anyone have an idea?

**Comment by inokappa** [comment]
@htnosm 

Thank you for your issue.

>I think it would be better to support testing with arn like lambda resource type.

👍 I also agree with that.

**Comment by inokappa** [comment]
Hi, all (@htnosm , @k1LoW )

I am planning to fix it with the following policy.

* Enable to specify domain name or ARN
* Returning exception error `Awspec :: DuplicatedResourceTypeError`, when domain name is duplicated

In Japanese.

以下のようなポリシーで修正しようと思います.

* ドメイン名又は ARN を指定可能にする
* ドメイン名が重複している場合, `Awspec :: DuplicatedResourceTypeError` を返す

htnosm さん, ありがとうございます 🙇

**Comment by htnosm** [comment]
Thank you for your support.

After updating, 
I confirmed the test success on ARN and duplication error at domain_name.

**Comment by inokappa** [comment]
@htnosm 

Thank you for your comment & check.
Closed.
