### ISSUE TITLE
Lamba :environment is unusable

### ISSUE THREAD

**Issue by glasswalk3r** [k1LoW/awspec#423]
Documentation at https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#lambda exposes the `:environment` to be with `its`, so if I tried something like:

```
expected = { "one" => 1, "two" => 2}

describe lambda('foobar') do
  it { should exist }
  its(:environment) { should eq expected }
  end
end
```

Things will not go as expected. `:environment` will return a `Aws::Lambda::Types::EnvironmentResponse` instance, which in fact has a `variables` attribute that could be used for comparison, but, as it is, the only way that comes to my mind in order to evaluate that is to manually create another `Aws::Lambda::Types::EnvironmentResponse`  instance.

Please let me know if I got this right, I would like to provide a PR to fix that.

**Comment by k1LoW** [comment]
@glasswalk3r Thank you !!! I want to test AWS Lambda environments too.

I want to test environments one by one. 

following

```ruby
describe lambda('foobar') do
  it { should exist }
  it { should have_environment("one").value("1") }
  it { should have_environment("two").value("2") }
end
```

How is this ?

**Comment by glasswalk3r** [comment]
Looks great @k1LoW !
I would only change `have_environment` by `have_env_var`:

```
describe lambda('foobar') do
  it { should exist }
  it { should have_env_var("one").value("1") }
  it { should have_env_var("two").value("2") }
end
```

**Comment by k1LoW** [comment]
I think `var` and `value` is duplicate meaning.

```ruby
it { should have_env_var("two").value("2") }
                     ^^^        ^^^^^
```

and following code should be **true**

```ruby
it { should have_env_var("two") } # not specify value
                     ^^^
```

for example

- Ruby lang have [ENV](https://docs.ruby-lang.org/en/trunk/ENV.html)
- Python lang have [os.environ](https://docs.python.org/3.7/library/os.html)
- aws cli (lambda) have `--environment` option

So, I like `have_environment`. 

What do you think?

**Comment by glasswalk3r** [comment]
@k1LoW , that's just a matter of style, but here is what I though about it:

`have_environment_variable -> have_env_var`

It is just a contraction, `var` stands for variable, not value. That's make very explicit that we are talking about a environment variable (since "environment" alone might but too generic) but your point of view might be different and that's OK too.

**Comment by k1LoW** [comment]
@glasswalk3r

> var stands for variable, not value.

> since "environment" alone might but too generic

Right! LGTM!! Thank you!!

**Comment by glasswalk3r** [comment]
Actually, `environment` **is** usable. My mistake.

One could use `have_attributes` standard RSpec Matcher for that:

```ruby
$ bundle exec rspec spec/type/lambda_spec.rb 
...............F...............

Failures:

  1) lambda 'my-lambda-function-name' environment should have attributes {"error" => nil, "variables" => {"ENDPOINT_URL" => "https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_...89:FoobarManager", "LOG_LEVEL" => "DEBUG", "RESOLVER1" => "10.196.138.1", "RESOLVER2" => "10.196.136.22"}}
     Failure/Error:
       its(:environment) { should have_attributes('error' => nil, 'variables' => {
         'ENDPOINT_URL' => 'https://foobar.sns.us-east-1.vpce.amazonaws.com',
         'ENV_NAME' => 'QA',
         'FOOBAR_TOPIC' => 'arn:aws:sns:us-east-1:123456789:FoobarManager',
         'LOG_LEVEL' => 'DEBUG',
         'RESOLVER1' => '10.196.138.1',
         'RESOLVER2' => '10.196.136.22'
         })}
     
       expected #<struct Aws::Lambda::Types::EnvironmentResponse variables={"ENDPOINT_URL" => "https://foobar.sns.us-ea...st-1:123456789:FoobarManager", "RESOLVER1" => "10.196.138.1", "RESOLVER2" => "10.196.136.2"}, error=nil> to have attributes {"error" => nil, "variables" => {"ENDPOINT_URL" => "https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_...89:FoobarManager", "LOG_LEVEL" => "DEBUG", "RESOLVER1" => "10.196.138.1", "RESOLVER2" => "10.196.136.22"}} but had attributes {"error" => nil, "variables" => {"ENDPOINT_URL" => "https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_...789:FoobarManager", "LOG_LEVEL" => "DEBUG", "RESOLVER1" => "10.196.138.1", "RESOLVER2" => "10.196.136.2"}}
       Diff:
       @@ -1,3 +1,3 @@
        "error" => nil,
       -"variables" => {"ENDPOINT_URL"=>"https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_NAME"=>"QA", "FOOBAR_TOPIC"=>"arn:aws:sns:us-east-1:123456789:FoobarManager", "LOG_LEVEL"=>"DEBUG", "RESOLVER1"=>"10.196.138.1", "RESOLVER2"=>"10.196.136.22"},
       +"variables" => {"ENDPOINT_URL"=>"https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_NAME"=>"QA", "FOOBAR_TOPIC"=>"arn:aws:sns:us-east-1:123456789:FoobarManager", "LOG_LEVEL"=>"DEBUG", "RESOLVER1"=>"10.196.138.1", "RESOLVER2"=>"10.196.136.2"},
       
     # ./spec/type/lambda_spec.rb:21:in `block (2 levels) in <top (required)>'

Finished in 0.08924 seconds (files took 1.9 seconds to load)
31 examples, 1 failure

Failed examples:

rspec ./spec/type/lambda_spec.rb:21 # lambda 'my-lambda-function-name' environment should have attributes {"error" => nil, "variables" => {"ENDPOINT_URL" => "https://foobar.sns.us-east-1.vpce.amazonaws.com", "ENV_...89:FoobarManager", "LOG_LEVEL" => "DEBUG", "RESOLVER1" => "10.196.138.1", "RESOLVER2" => "10.196.136.22"}}
```

I updated the related stub (`lib/awspec/stub/lambda.rb`) on my own branch to include more data and forced the tests to fail to show the error report. Of course, this wasn't nearly looking good as it would with `have_env_var`, but yes, it could be tested like this, as for any other struct returned by the AWS SDK.

**Comment by glasswalk3r** [comment]
It seems complicated to implement a new matcher `have_env_var` that allows an invocation like `have_env_var("two").value("2")`: it would have to return, for instance, an `Struct` (that will always be `true` due the `object_id`) if the environment variable exists and associate a value method with it.
The problem is the cases where the environment variable doesn't exist: it would need to return `false`, but the `FalseClass` hasn't a `value` method and that would raise a `NoMethodError`, which would be crypt in the test result.
Then I could use the Open Class concept and add a `value` method to the `FalseClass`, but messing with such important class could be dangerous, I guess:

```ruby
[7] pry(main)> false.class
=> FalseClass
[8] pry(main)> class FalseClass
[8] pry(main)*   def value
[8] pry(main)*     raise "No such environment variable"
[8] pry(main)*   end  
[8] pry(main)* end  
=> :value
[9] pry(main)> if false
[9] pry(main)*   puts 'false'
[9] pry(main)* end  
=> nil
[10] pry(main)> false.object_id
=> 0
[11] pry(main)> unless false
[11] pry(main)*   puts 'false'
[11] pry(main)* end  
false
=> nil
[12] pry(main)> false.value
RuntimeError: No such environment variable
from (pry):10:in `value'
```

Anyway, the test would not fail, but be aborted. Conceptually speaking, I guess we would prefer the former as a result.

If there is a safer way to implement that, I'm all ears. Otherwise, I strongly suggest to use two new matchers:

- `have_env_var` that takes a string of the environment variable name as parameter and returns `true` or `false`.
- `have_env_var_value` (or something like that) that takes both the environment variable name and the respective value as parameters and returns `true` or `false`.
