### ISSUE TITLE
ssm parameters does not work when ssm parameters are paginated

### ISSUE THREAD

**Issue by tozonaran** [k1LoW/awspec#443]
When you have ssm parameters > 50 in your aws account, then parameters "on the second page" are not found

I had a similar issue with the AWS Cli where results are paginated to 50 results per "page".

https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters-by-path.html
https://docs.aws.amazon.com/cli/latest/userguide/cli-usage-pagination.html

**Comment by tozonaran** [comment]
Is there a --recursive param I can use?

**Comment by tozonaran** [comment]
Looks like this is where the issue is https://github.com/k1LoW/awspec/blob/master/lib/awspec/helper/finder/ssm_parameter.rb#L13
I will try to fix in my spare time.

**Comment by tozonaran** [comment]
Can anybody help me with this? here is my fix https://github.com/tozonaran/awspec/commit/4eac251835f72f76ab0160a6e73f3772fc9158a4

I had issues with updating the unit tests to reflect my new changes.

**Comment by cthulhu** [comment]
Created PR, pls take a look. We monkey patched for our specs so far:
https://github.com/k1LoW/awspec/pull/481
