### ISSUE TITLE
Check if file exists in ec2 instance

### ISSUE THREAD

**Issue by felipem1210** [k1LoW/awspec#496]
Hi, I'm using awspec to make some tests in my terraform code for aws infrastructure. I want to know if there is any way or method to test if some files are present in an ec2 instance I create.

Best regards

**Comment by bplunkert** [comment]
I'm new to AWSpec, so there might be ways I'm not aware of, but I think you might find Serverspec is a better fit for this kind of instance-level testing.

**Comment by felipem1210** [comment]
@bplunkert Thank you, that helped me a lot
