### ISSUE TITLE
 Questions about template creation

### ISSUE THREAD

**Issue by BFTnaito** [k1LoW/awspec#584]
I have a few questions regarding the content mentioned in the following URL's README:

https://github.com/k1LoW/awspec/blob/master/README.md#advanced-tips-spec-generate-command

Regarding the $ awspec generate ec2 vpc-ab123cde >> spec/ec2_spec.rb command:

1.Can this command only be used if the AWS resource already exists?
2.Can the template be generated if the AWS resource does not yet exist?
3.Are the detailed parameters of the generated template limited to those mentioned in the URL (https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md), or does it cover all parameters of the AWS resource?

**Comment by k1LoW** [comment]
Hi!

> 1.Can this command only be used if the AWS resource already exists?

Yes.

> 2.Can the template be generated if the AWS resource does not yet exist?

No.

> 3.Are the detailed parameters of the generated template limited to those mentioned in the URL (https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md), or does it cover all parameters of the AWS resource?

No.

awspec is a READ Only tool for AWS resources.

Please try it out!

**Comment by BFTnaito** [comment]
Thank you for your response.
Regarding your answer (3), do you mean that it doesn't cover all parameters of the AWS resource?

**Comment by k1LoW** [comment]
> Regarding your answer (3), do you mean that it doesn't cover all parameters of the AWS resource?

Yes. Not all are supported.
