### ISSUE TITLE
how to test tags?

### ISSUE THREAD

**Issue by BFTnaito** [k1LoW/awspec#585]
When I run ''bundle exec awspec generate vpc xxx-VPC --region=xx'' to test a VPC, the configuration values regarding tags is not output.
Why are the configuration values related to tags not outputted? Of course, tags are assigned to a VPC.
Is it possible to run tests on tags in this case?

**Comment by BFTnaito** [comment]
So, we can test tags, even though they are not outputted in a template, right?

**Comment by k1LoW** [comment]
Yes.
See https://github.com/k1LoW/awspec/blob/master/doc/resource_types.md#have_tag-28 👍
